### ISSUE TITLE
No space between navigation and page content on mobile

### ISSUE THREAD

**Issue by ferdesmannen** [TryGhost/Lyra#30] opened 2019-12-21 12:58 UTC
Affects both tag and author page.

https://github.com/TryGhost/Casper/issues/654

Only an issue on Lyra, not on Casper.

**Comment by TheodoreChu** [comment] 2020-02-14 09:11
Yeah, there's definitely a problem with the header on Lyra that's not on Casper. I noticed that the problem is not as bad, though still present, when the tag page has an image on top.

**Comment by TheodoreChu** [comment] 2020-02-20 00:33
It looks like this was improved with https://github.com/TryGhost/Lyra/commit/e94daab78777a439ab310d70efd7172d9cc4a321. Thank you @peterzimon

**Comment by kevinansfield** [comment] 2020-02-20 10:06
Resolved in https://github.com/TryGhost/Lyra/commit/e94daab78777a439ab310d70efd7172d9cc4a321

**Closed by kevinansfield** 2020-02-20 10:06 UTC
